[package]
name = "learn_gfx_hal"
version = "0.1.0"
authors = ["Tim Harding <account@timharding.co>"]
edition = "2018"

[dependencies]
gfx-hal = "^0"
gfx-backend-vulkan = "^0"
winit = "^0"
log = "^0"
simple_logger = "^1"
arrayvec = "^0"